# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSwGjAnai5vhQ8ADSJh9U843i0vKyHqh
"""

from flask import Flask, request, jsonify
import joblib
import pandas as pd

# ── Model ko ek hi dafa load karein ───────────────────────────────────────
MODEL_PATH = "model.pkl"
model = joblib.load(MODEL_PATH)

app = Flask(__name__)

def make_prediction(input_json):
    """
    input_json example:
      {
        "url": "/search?q='OR 1=1-- -",
        "firedtimes": 1,
        "level": 6
      }
    """
    # Features DataFrame
    df = pd.DataFrame([{
        "url": input_json.get("url", ""),
        "firedtimes": input_json.get("firedtimes", 1),
        "level": input_json.get("level", 1)
    }])

    # Model predict
    pred = model.predict(df)[0]
    return "real threat" if pred == 1 else "false positive"

# ── Flask endpoint ────────────────────────────────────────────────────────
@app.route("/predict", methods=["POST"])
def predict():
    if not request.is_json:
        return jsonify({"error": "No input data provided"}), 400

    data = request.get_json()
    required = {"url", "firedtimes", "level"}
    missing = required - data.keys()
    if missing:
        return jsonify({"error": f"Missing field(s): {', '.join(missing)}"}), 400

    try:
        result = make_prediction(data)
        return jsonify({"prediction": result})
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ── Run server ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 10000))  # Render ya local
    app.run(host="0.0.0.0", port=port, debug=True)